detailed_crime_scene_task:
  description: >
    Generate a detailed description of the crime scene for a murder mystery set in the context of "{topic}" during the year {year}. 
    Include the following details: the victim's identity (name, age, occupation, and background), the time of death, the location of the crime, 
    the condition of the body when found, any evidence present at the scene, and the initial observations of the surroundings. 
    Ensure the description is vivid and sets the tone for the mystery.
  expected_output: >
    A detailed crime scene description in Markdown format:
    ## Victim Details
    - Name:
    - Age:
    - Occupation:
    - Background:
    ## Time of Death
    ## Location
    ## Body Condition
    ## Evidence Found
    ## Surroundings
  agent: crime_scene_investigator

character_modification_task:
  description: >
    Modify the given characters({characters}) to make them suspects in a murder case set in the context of "{topic}" during the year {year}. 
    Each character should have a detailed profile, backstory, distinct personality traits, and a plausible motive for the crime. 
    Ensure that none of the characters take on roles such as detectives or investigators.
  expected_output: >
    A detailed list of modified characters in Markdown format, with the following structure for each suspect:
    ## Suspect
    - **Name**: 
    - **Age**: 
    - **Gender**: 
    - **Occupation**: 
    - **Background**: 
    - **Relationship with the Victim**: 
    - **Motive for the Crime**: 
  agent: casting_director

murder_case_outline_task:
  description: >
    Create a murder mystery story set in the year {year}, based on the topic "{topic}". 
    The story should involve {character_amount} suspects, each with a clear motive for killing the victim. 
    Make the story engaging with simple yet intriguing twists, avoiding overly complex vocabulary. 
    Ensure that the true culprit is one of the {character_amount} suspects. 
    Include detailed information about the victim's identity, the crime scene, the suspects, and how the true culprit committed the murder.
  expected_output: >
    ## Crime Scene
    ## Suspect Profiles
    ## True Culprit
  agent: plot_weaver

# plot_weaving_task:
#   description: >
#     Based on the input text, generate a more detailed and enriched story that includes:
#     1. The background story of the victim and each suspect, highlighting their relationships and interactions.
#     2. A detailed account of the events on the day of the victim's death, including how everyone gathered together and the circumstances leading to the victim's demise.
#     3. A timeline for each suspect's activities on the day of the murder, along with their possible methods of committing the crime.
#     4. A clear and detailed explanation of how the victim ultimately died.
#   expected_output: >
#     A richly detailed story
#   agent: plot_weaver

# detail_enhancement_task:
#   description: >
#     Enhance the plot by adding vivid details, reliable suspenseful reasoning, and ensure every character has meaningful involvement in the story.
#   expected_output: >
#     A more detailed and engaging version of the input text, enriched with details.
#   agent: detail_enhancer

# structured_story_task:
#   description: >
#     Organize the text into a structured format using Markdown: first, outline the overall story; Next, provide descriptions of all characters; 
#     finally, provide a detailed version of the story.
#   expected_output: >
#     A structured document in Markdown format containing: 
#     ## Story Outline
#     - A concise and compelling story outline. Include the time, location, crime scene and the identification of the victim. 

#     ## Suspect Descriptions
#     - Descriptions of all suspects, including their age, gender, relationship with the victim, and background story.
    
#     ## Suspect Timelines
#     - A timeline for each suspect's activities on the day of the murder, along with their possible methods of committing the crime.
    
#     ## Culprit Details
#     - The identity of the true culprit, with a clear explanation of their motive and method of committing the murder.
#   agent: plot_weaver

# english_to_chinese_translation_task:
#   description: >
#     Translate the given English text into Chinese.
#   expected_output: >
#     The translated text in Chinese, accurately reflecting the original English content. No English content after translation.
#   agent: english_to_chinese_translator