character_creation_task:
  description: >
    Generate {character_amount} unique characters for the murder mystery.
    Each character should have a backstory, personality traits, and potential motives.
  expected_output: >
    A list of {character_amount} characters, each with a detailed backstory, personality, and motives.
  agent: casting_director

plot_weaving_task:
  description: >
    Create a compelling script or story outline for the murder mystery centered around {topic}.
    Ensure the story has engaging twists, clear motives, and a logical flow.
  expected_output: >
    A detailed story outline or script with key plot points, twists, and character motivations, all revolving around {topic}.
  agent: plot_weaver

detail_enhancement_task:
  description: >
    Enhance the plot by adding vivid details, reliable suspenseful reasoning, and ensure every character has meaningful involvement in the story.
  expected_output: >
    A more detailed and engaging version of the input text, enriched with details.
  agent: detail_enhancer

structured_story_task:
  description: >
    Organize the text into a structured format: first, provide descriptions of all characters; 
    next, outline the overall story; finally, provide outlines for each Act in the story.
  expected_output: >
    A structured document containing: 
    1. Descriptions of all characters.
    2. An overall story outline.
    3. Detailed outlines for each Act in the story.
  agent: plot_weaver

english_to_chinese_translation_task:
  description: >
    Translate the given English text into Chinese.
  expected_output: >
    The translated text in Chinese, accurately reflecting the original English content. No English content after translation.
  agent: english_to_chinese_translator
